// <auto-generated />
using System;
using DrinksWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrinksWebApp.Migrations
{
    [DbContext(typeof(DrinksAppContext))]
    [Migration("20230207153244_userDrinkField")]
    partial class userDrinkField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("DrinksWebApp.Models.AlcoholIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlcoholVolume")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlcoholIngredient", (string)null);
                });

            modelBuilder.Entity("DrinksWebApp.Models.AlcoholIngredientDrink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlcoholIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DrinkId" }, "IXFK_AlcoholIngredientDrink_Drink");

                    b.HasIndex(new[] { "AlcoholIngredientId" }, "IXFK_AlcoholIngredientDrink_Ingredient");

                    b.HasIndex(new[] { "DrinkId", "AlcoholIngredientId" }, "UQ_AlcoholIngredientDrink_IngredientDrinkId")
                        .IsUnique();

                    b.ToTable("AlcoholIngredientDrink", (string)null);
                });

            modelBuilder.Entity("DrinksWebApp.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IXFK_Drink_User");

                    b.ToTable("Drink", (string)null);
                });

            modelBuilder.Entity("DrinksWebApp.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("DrinksWebApp.Models.IngredientDrink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DrinkId" }, "IXFK_IngredientDrink_Drink");

                    b.HasIndex(new[] { "IngredientId" }, "IXFK_IngredientDrink_Ingredient");

                    b.HasIndex(new[] { "DrinkId", "IngredientId" }, "UQ_IngredientDrink_IngredientDrinkId")
                        .IsUnique();

                    b.ToTable("IngredientDrink", (string)null);
                });

            modelBuilder.Entity("DrinksWebApp.Models.Opinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DrinkId" }, "IXFK_Opinion_Drink");

                    b.HasIndex(new[] { "UserId" }, "IXFK_Opinion_User");

                    b.ToTable("Opinion", (string)null);
                });

            modelBuilder.Entity("DrinksWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DrinksWebApp.Models.AlcoholIngredientDrink", b =>
                {
                    b.HasOne("DrinksWebApp.Models.AlcoholIngredient", "AlcoholIngredient")
                        .WithMany("AlcoholIngredientDrinks")
                        .HasForeignKey("AlcoholIngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_AlcoholIngredientDrink_AlcoholIngredient");

                    b.HasOne("DrinksWebApp.Models.Drink", "Drink")
                        .WithMany("AlcoholIngredientDrinks")
                        .HasForeignKey("DrinkId")
                        .IsRequired()
                        .HasConstraintName("FK_AlcoholIngredientDrink_Drink");

                    b.Navigation("AlcoholIngredient");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("DrinksWebApp.Models.Drink", b =>
                {
                    b.HasOne("DrinksWebApp.Models.User", "User")
                        .WithMany("Drinks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Drink_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DrinksWebApp.Models.IngredientDrink", b =>
                {
                    b.HasOne("DrinksWebApp.Models.Drink", "Drink")
                        .WithMany("IngredientDrinks")
                        .HasForeignKey("DrinkId")
                        .IsRequired()
                        .HasConstraintName("FK_IngredientDrink_Drink");

                    b.HasOne("DrinksWebApp.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientDrinks")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_IngredientDrink_Ingredient");

                    b.Navigation("Drink");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("DrinksWebApp.Models.Opinion", b =>
                {
                    b.HasOne("DrinksWebApp.Models.Drink", "Drink")
                        .WithMany("Opinions")
                        .HasForeignKey("DrinkId")
                        .IsRequired()
                        .HasConstraintName("FK_Opinion_Drink");

                    b.HasOne("DrinksWebApp.Models.User", "User")
                        .WithMany("Opinions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Opinion_User");

                    b.Navigation("Drink");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DrinksWebApp.Models.AlcoholIngredient", b =>
                {
                    b.Navigation("AlcoholIngredientDrinks");
                });

            modelBuilder.Entity("DrinksWebApp.Models.Drink", b =>
                {
                    b.Navigation("AlcoholIngredientDrinks");

                    b.Navigation("IngredientDrinks");

                    b.Navigation("Opinions");
                });

            modelBuilder.Entity("DrinksWebApp.Models.Ingredient", b =>
                {
                    b.Navigation("IngredientDrinks");
                });

            modelBuilder.Entity("DrinksWebApp.Models.User", b =>
                {
                    b.Navigation("Drinks");

                    b.Navigation("Opinions");
                });
#pragma warning restore 612, 618
        }
    }
}
